# Generated by Django 5.1.2 on 2024-11-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_frasemodel_options_alter_frasemodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='autormodel',
            name='profesion',
        ),
        migrations.AddField(
            model_name='autormodel',
            name='profesion',
            field=models.ManyToManyField(to='App1.profesion', verbose_name='Profesión'),
        ),
    ]
